version: '3.5'
services:
  ibdiscord_verify:
    build: .
    env_file: details.env
    restart: always
    depends_on:
     - redis
    networks: 
     - web

  redis:
    image: redis

networks:
  web:
    external: true
