version: '3.5'
services:
  ibdiscord_verify:
    build: .
    env_file: details.env
    restart: always
    depends_on:
     - redis
    networks: 
     - web
     - backend

  redis:
    image: redis
    networks: 
     - backend

networks:
  backend:
    external: false
  web:
    external: true
