version: '3.5'
services:
  app:
    build: .
    image: app
    ports:
    - '80:80'
    networks:
    - com
    env_file: details.env
    depends_on:
    - redis
  redis:
    image: redis
    volumes:
    - 'redis:/data'
volumes:
  redis:
networks:
  com: